development:
  host: 127.0.0.1
  adapter: mysql
  database: kmi9_vekwak90_dev
  username: root
  encoding: utf8
  timeout: 5000

test:
  host: 127.0.0.1
  adapter: mysql
  database: kmi9_vekwak90_test
  username: root
  encoding: utf8
  timeout: 5000

production:
  host: 127.0.0.1
  adapter: mysql
  database: kmi9_vekwak90_prod
  username: root
  encoding: utf8
  timeout: 5000
