development:
  host: 127.0.0.1
  adapter: mysql
  database: kmi9_vekwak90
  username: root
  encoding: utf8
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  host: mysql0.locum.ru	
  adapter: mysql
  database: kmi9_vekwak90
  username: kmi9_vekwak90
  password: MTjNrEQi
  encoding: utf8
  timeout: 5000
